Proyecto de Asistencias (2)/Proyecto de Asistencias/Controllers/InstructorMenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto_de_Asistencias.Sesion;
using Libreria_de_conexion;
using System.Data.SqlClient;
using System.Data;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using System.IO;
using System.Data.Entity;

namespace Proyecto_de_Asistencias.Controllers
{
    [Validar_sesion]
    public class InstructorMenuController : Controller
    {
        private AsistenciaEntities db = new AsistenciaEntities();

        Aprendiz apr = new Aprendiz(); 
  
        
        // GET: InstructorMenu
        public ActionResult MenuprincipalInstructor()
        {
            return View();
        }
        public ActionResult VistaAsistencias()
        {
            return View();
        }
        public ActionResult VistaInasistencias()
        {
            return View();
        } 
        public ActionResult Consultar_Asistencia()
        {

            ViewBag.Fichas = db.Ficha.Select(f => new SelectListItem
            {
                Value = f.Numero_Ficha.ToString(),
                Text = f.Numero_Ficha.ToString()
            }).ToList();

            return View();
        }
     
        public ActionResult ConsultarFichas()
        {
            return View();
        }
        public ActionResult VistaconsultarInasistencias()
        {
            return View();

        }
        public ActionResult Listadofichas()
        {
            return View();
        }
        public ActionResult ListadoAprendiCES()
        { 
            return View();

        }
        public ActionResult ListadoProgramas()
        {
            return View();
        }
        public ActionResult ListadoCompetencias()
        {
            return View();
        }
        public ActionResult Reporte()
        {
            
            return View();
           
        }
        public ActionResult ConsultarArchivo()
        {
            using (var db = new AsistenciaEntities())
            {

                var aprendices1 = db.Soporte_asistencia.Where(a => a.idAsistencia == a.idAsistencia)
                                           .Include(a => a.Aprendiz)
                                           .Include(a => a.Registro_Asistencias_QR)
                    .ToList();


                ViewBag.Aprendiz = aprendices1;


            }


            return View();

        }
        public ActionResult Descargars(int id)
        {
            var soporte = db.Soporte_asistencia.Find(id);
            if (soporte == null || soporte.Archivo_soporte == null)
            {
                return HttpNotFound();
            }

            var archivoBytes = soporte.Archivo_soporte;
            var contentType = "application/pdf";

            return File(archivoBytes, contentType);
        }



        // Acción para previsualizar el reporte en un iframe
        public ActionResult Previsualizar(DateTime fecha)
        {
            try
            {
                // Obtener el ID del instructor desde la sesión
                int instructorId = (int)Session["Instructor"];

                // Crear una instancia de ReportClass para el reporte de asistencia
                var rpth = new ReportClass();
                // Establecer la ruta del archivo del reporte
                string reportPath = Server.MapPath("/Reportes/Reporteasistencia.rpt");
                rpth.FileName = reportPath;

                // Verificar si el archivo existe
                if (!System.IO.File.Exists(reportPath))
                {
                    throw new FileNotFoundException("El archivo del reporte no fue encontrado.", reportPath);
                }

                // Cargar el archivo del reporte
                rpth.Load();

                // Configurar la información de conexión a la base de datos
                var connInfo = new ConnectionInfo
                {
                    IntegratedSecurity = true, // Usar seguridad integrada de Windows
                    ServerName = @"JAMB\SQLEXPRESS", // Nombre del servidor de base de datos
                    DatabaseName = "Asistencia" // Nombre de la base de datos
                };

                // Aplicar la configuración de conexión a cada tabla del reporte
                foreach (Table table in rpth.Database.Tables)
                {
                    var logonInfo = table.LogOnInfo;
                    logonInfo.ConnectionInfo = connInfo;
                    table.ApplyLogOnInfo(logonInfo);
                }

                // Establecer los parámetros del ID del instructor y la fecha en el reporte
                rpth.SetParameterValue("@InstructorId", instructorId);
                rpth.SetParameterValue("@Fecha", fecha);

                // Exportar el reporte a un stream en formato PDF
                Stream stream = rpth.ExportToStream(ExportFormatType.PortableDocFormat);
                stream.Seek(0, SeekOrigin.Begin);

                // Retornar el stream del PDF como un resultado de archivo
                return new FileStreamResult(stream, "application/pdf");
            }
            catch (Exception ex)
            {
                // Registrar el error para el diagnóstico
                System.Diagnostics.Trace.TraceError($"Error al generar el reporte: {ex.Message}\n{ex.StackTrace}");

                // En caso de error, retornar un código de estado HTTP 500 con un mensaje de error
                return new HttpStatusCodeResult(500, $"Error al generar el reporte: {ex.Message}");
            }
        }

        


        public ActionResult QrAsistencias()
        {
            return View();
        }

        public ActionResult InasistenciasAprendiz()
        {
            return View();
        }
        public ActionResult ConsultarProgramas()
        {
            return View();
        }
        public ActionResult ConsultarCompetencias()
        {
            return View();
        }
        public ActionResult FormularioAsistencias()
        {
            return View(); 
        }  
       
       
        public ActionResult RegistroInasistencia()
        {
            // Obtiene todas las fichas de la base de datos y las convierte en una lista de elementos SelectListItem.
            // Estos elementos se utilizan para llenar un menú desplegable en la vista.
            ViewBag.Fichas = db.Ficha.Select(f => new SelectListItem
            {
                Value = f.Numero_Ficha.ToString(),
                Text = f.Numero_Ficha.ToString()
            }).ToList();


            // Retorna la vista.
            return View();
        }


        public ActionResult GetProgramasPorFicha(int fichaId)
        {

            // Este método se encarga de obtener los programas asociados a una ficha específica.
            // Obtiene todas las fichas de la base de datos que coinciden con el id de la ficha proporcionado.
            // Luego, selecciona el id y el nombre del programa asociado a cada ficha.
            // Finalmente, elimina los duplicados y convierte el resultado en una lista.
            var programas = db.Ficha
                              .Where(f => f.Numero_Ficha == fichaId)
                              .Select(f => new {
                                  f.Programa_Formacion.idPrograma,
                                  f.Programa_Formacion.Nombre_Programa
                              })
                              .Distinct()
                              .ToList();

            // Retorna los programas como un objeto JSON.
            return Json(programas, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetCompetenciasPorPrograma(int programaId)
        {
            // Este método se encarga de obtener las competencias asociadas a un programa específico.
            // Obtiene todas las competencias de la base de datos que coinciden con el id del programa proporcionado.
            // Luego, selecciona el id y el nombre de cada competencia.
            // Finalmente, convierte el resultado en una lista.
            var competencias = db.Competencia
                                 .Where(c => c.idPrograma == programaId)
                                 .Select(c => new { c.idCompetencia, c.Nombre_Competencia })
                                 .ToList();
            // Retorna las competencias como un objeto JSON.
            return Json(competencias, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetAprendicesPorFicha(int fichaId)
        {
            // Este método se encarga de obtener los aprendices asociados a una ficha específica.
            // Obtiene todos los aprendices de la base de datos que coinciden con el número de ficha proporcionado.
            // Luego, selecciona el id y el nombre completo (nombres y apellidos) de cada aprendiz.
            // Finalmente, convierte el resultado en una lista.
            var aprendices = db.Aprendiz
                .Where(a => a.Numero_Ficha == fichaId)
                .Select(a => new
                {
                    a.idAprendiz,
                    NombreCompleto = a.Nombres_Aprenidiz + " " + a.Apellidos_Aprendiz
                })
                .ToList();
            // Retorna los aprendices como un objeto JSON.
            return Json(aprendices, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult RegistrarInasistencia(int fichaId, int programaId, string nombreCompetencia, int aprendizId, string fecha, string hora)
        {
            try
            {
                // Obtener el id del instructor desde la sesión
                var idInstructor = Session["Instructor"];
                // Si el instructor no está autenticado, se devuelve un mensaje de error
                if (idInstructor == null)
                {
                    return Json(new { success = false, message = "Instructor no autenticado" });
                }

Proyecto de Asistencias (2)/Proyecto de Asistencias/Views/InstructorMenu/ConsultarAprendices.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ConsultarAprendices</title>
</head>
<body>
    <form action="@Url.Action("ConsultarA", "InstructorMenu")">
        <div>
            <label>Numero de ficha</label>
            <input name="NumeroFicha" placeholder="Numero de ficha" />
        </div>
        <div>
            <label>id de Competencia</label>
            <input name="IdCompetencia" placeholder="Id de Competencia" />
        </div>
        <div>
            <label>Id de Programa</label>
            <input name="IdPrograma" placeholder="Id de Programa" />
        </div>
        <div>
            <button type="submit">Consultar</button>
        </div>
    </form>
</body>

    

</html>

Proyecto de Asistencias (2)/Proyecto de Asistencias/Views/InstructorMenu/ConsultarArchivo.cshtml
@{ Layout = null;
    var nombreUsuario = Session["NombreUsuario"] as string ?? "Nombre";
    var apellidoUsuario = Session["ApellidoUsuario"] as string ?? "Apellido";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Consultar Archivo Soportes</title>
    <link href="~/CSS/CSSvistasInstructor.css" rel="stylesheet" />
</head>
<body>
    <header>
    </header>
    <section>
        <div class="container">
            <div class="header">
                <h1>Apendiz @nombreUsuario @apellidoUsuario</h1>
                <h4>Consultar Archivo Soporte</h4>
            </div>
            <div>
                <div class="cuadrado">


                    <table>
                        <thead>
                            <tr>
                                <th>Id de Soporte</th>
                                <th>Nombre de Aprendiz</th>
                                <th>Apellidos de Aprendiz</th>
                                <th>Archivo Soporte</th>
                                <th>Fecha y Hora</th>
                                <th>Id de Asistencia</th>
                            </tr>
                        </thead>

                        <tbody>


                            @foreach (var aprendiz in ViewBag.Aprendiz)
                            {
                                <tr>

                                    <td>@aprendiz.idSoporte</td>
                                    <td>@aprendiz.Aprendiz.Nombres_Aprenidiz</td>
                                    <td>@aprendiz.Aprendiz.Apellidos_Aprendiz</td>
                                    @if (aprendiz.Archivo_soporte != null)
                                    {
                                        <td>  <a href="@Url.Action("Descargars", "InstructorMenu", new { id = aprendiz.idSoporte  })">Ver Archivo</a></td>
                                    }
                                    else
                                    {
                                        <td>No hay Archivo disponible</td>
                                    }


                                    <td>@aprendiz.Fecha_Hora</td>
                                    <td>@aprendiz.idAsistencia</td>

                                </tr>


                            }
                        </tbody>
                        <!-- Puedes añadir más filas según sea necesario -->
                    </table>
                </div>
                <div class="">
                    <button class="button" onclick="location.href = 'MenuprincipalInstructor'">Volver</button>
                </div>
            </div>

           
        </div>
    </section>

    <footer>
        Assist.NET
    </footer>
</body>
</html>

Proyecto de Asistencias (2)/Proyecto de Asistencias/Views/InstructorMenu/ConsultarInasistencias.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ConsultarInasistencias</title>
    @*<link href="~/CSS/ConsultarInasistencia.css" rel="stylesheet" />*@
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    @*<link href="~/CSS/VistasInstructor.css" rel="stylesheet" />*@
    <link href="~/CSS/EstiloConsultarI.css" rel="stylesheet" />
</head>
<body>
    <header>
    </header>
    <section>

        <div class="container">
            <div class="header">
                <h1>Instructor Jesus Marzal Barboza</h1>
                <h2>Listado de Inasistencias</h2>
                <h4>Consulta Inasistencia</h4>
            </div>

            <div class="form-field">
                <label for="fecha">Fecha:</label>
                <input type="date" id="fecha" name="fecha">

            </div>

            <div class="form-container">
                <div class="ficha">
                    <label for="ficha">Seleccione el número de la Ficha</label>
                    <select id="ficha" class="form-control">
                        <option value="">Seleccione una ficha</option>
                        @foreach (var item in ViewBag.Fichas)
                        {
                            <option value="@item.Value">@item.Text</option>
                        }
                    </select>
                </div>
                <div class="programa">
                    <label for="programa_formacion">Seleccione el programa de formación:</label>
                    <select id="programa_formacion" class="form-control">
                        <option value="">Seleccione un programa</option>
                    </select>
                </div>
                <div class="competencia">
                    <label for="competencias">Seleccione la competencia:</label>
                    <select id="competencias" class="form-control">
                        <option value="">Seleccione una competencia</option>
                    </select>
                </div>
                <button id="buscar-inasistencias" class="btn btn-primary">Mostrar Inasistencias</button>
            </div>
            <div class="cuadrado">
                <table class="custom-table">
                    <thead>
                        <tr>
                            <th>Nombres de Aprendiz</th>
                            <th>Apellidos de Aprendiz</th>
                            <th>Fecha</th>
                            <th>Ficha</th>
                            <th>Programa de Formacion</th>
                            <th>Competencia</th>
                        </tr>
                    </thead>
                    <tbody id="inasistencias-table-body">
                        <!-- Filas de inasistencias se llenarán dinámicamente aquí -->
                    </tbody>
                </table>
            </div>
            <div class="">
                <button class="button" onclick="location.href = 'MenuprincipalInstructor'">Volver</button>
            </div>
        </div>

    </section>
    <footer>
        Assist.NET
    </footer>
    <script>
        // Este bloque de código se ejecuta cuando el documento HTML ha sido completamente cargado y está listo para interactuar con JavaScript.
        $(document).ready(function () {
             // Este bloque de código se ejecuta cuando el valor del elemento HTML con id 'ficha' cambia. Este elemento es un menú desplegable.
            $('#ficha').change(function () {
                 // Aquí se obtiene el valor del elemento HTML con id 'ficha'. Este valor es el Numero de la ficha seleccionada por el usuario.
                var fichaId = $(this).val();
                 // Los siguientes dos bloques de código vacían los elementos HTML con ids 'programa_formacion', 'competencias' y les añaden una opción por defecto.
                $('#programa_formacion').empty().append('<option value="">Seleccione un programa</option>');
                $('#competencias').empty().append('<option value="">Seleccione una competencia</option>');
                 // Si el id de la ficha es válido (no está vacío), se realiza una solicitud AJAX para obtener los programas correspondientes a la ficha.
                if (fichaId) {
                    $.ajax({
                         // La URL a la que se envía la solicitud AJAX.
                        url: '@Url.Action("GetProgramasPorFicha", "InstructorMenu")',
                        // El tipo de solicitud HTTP a realizar. En este caso, es una solicitud GET.
                        type: "GET",
                         // Los datos que se envían al servidor en la solicitud HTTP. En este caso, se envía el id de la ficha.
                        data: { fichaId: fichaId },
                        // Esta función se ejecuta si la solicitud AJAX se completa con éxito. Los datos devueltos por el servidor se pasan a esta función
                        success: function (data) {
                              // Aquí se obtiene una referencia al elemento HTML con id 'programa_formacion'.
                            var $programaFormacion = $('#programa_formacion');
                            // Esta función de jQuery itera sobre los datos devueltos por el servidor. En cada iteración,
                            //se añade una nueva opción al elemento 'programa_formacion' con el id y el nombre del programa.
                            $.each(data, function (index, value) {
                                $programaFormacion.append('<option value="' + value.idPrograma + '">' + value.Nombre_Programa + '</option>');
                            });
                        }
                    });
                }
            });
            // Este bloque de código se ejecuta cuando el valor del elemento HTML con id 'programa_formacion' cambia.
            $('#programa_formacion').change(function () {
                 // Aquí se obtiene el valor del elemento HTML con id 'programa_formacion'. Este valor es el programa seleccionado por el usuario.
                var programaId = $(this).val();
                 // El siguiente bloque de código vacía el elemento HTML con id 'competencias' y le añade una opción por defecto.
                $('#competencias').empty().append('<option value="">Seleccione una competencia</option>');
                 // Si el id del programa es válido (no está vacío), se realiza una solicitud AJAX para obtener las competencias correspondientes al programa.
                if (programaId) {
                    $.ajax({
                        url: '@Url.Action("GetCompetenciasPorPrograma", "InstructorMenu")',
                        type: "GET",
                        data: { programaId: programaId },
                         // Esta función se ejecuta si la solicitud AJAX se completa con éxito. Los datos devueltos por el servidor se pasan a esta función.
                        success: function (data) {
                             // Aquí se obtiene una referencia al elemento HTML con id 'competencias'.
                            var $competencias = $('#competencias');
                            // Esta función de jQuery itera sobre los datos devueltos por el servidor. En cada iteración,
                            //se añade una nueva opción al elemento 'competencias' con el id y el nombre de la competencia.
                            $.each(data, function (index, value) {
                                $competencias.append('<option value="' + value.idCompetencia + '">' + value.Nombre_Competencia + '</option>');
                            });
                        }
                    });
                }
            });
            // Este bloque de código se ejecuta cuando se hace clic en el elemento HTML con id 'buscar-inasistencias'
            $('#buscar-inasistencias').click(function () {
                 // Aquí se obtienen los valores de los elementos HTML con ids 'ficha', 'programa_formacion' y 'competencias'.
                var fichaId = $('#ficha').val();
                var programaId = $('#programa_formacion').val();
                var competenciaId = $('#competencias').val();
                var fecha = $('#fecha').val(); // Nuevo campo de fecha
                // Se realiza una solicitud AJAX para obtener las inasistencias correspondientes a los valores seleccionados.
                $.ajax({
                    url: '@Url.Action("ObtenerInasistencias", "InstructorMenu")',
                    type: "GET",
                    data: {
                        fichaId: fichaId || null,
                        programaId: programaId || null,
                        competenciaId: competenciaId || null,
                        fecha: fecha || null
                    },
                    success: function (data) {
                        // Aquí se obtiene una referencia al cuerpo de la tabla HTML con id 'inasistencias-table-body'.
                        var $tbody = $('#inasistencias-table-body');
                        // Se vacía el cuerpo de la tabla.
                        $tbody.empty();
                        // Esta función de jQuery itera sobre los datos devueltos por el servidor. En cada iteración,
                        //se añade una nueva fila a la tabla con los datos de la inasistencia.
                        $.each(data, function (index, value) {
                            var row = '<tr>' +
                                '<td>' + value.Nombre + '</td>' +
                                '<td>' + value.Apellidos + '</td>' +
                                '<td>' + value.Fecha + '</td>' +
                                '<td>' + value.Ficha + '</td>' +
                                '</tr>';
                            $tbody.append(row);
                        });
                    }
                });
            });
        });
    </script>
</body>
</html>

Proyecto de Asistencias (2)/Proyecto de Asistencias/Views/InstructorMenu/ConsultarProgramas.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Consultar Programas</title>
    <link href="~/CSS/CSSvistasInstructor.css" rel="stylesheet" />
    <link href="~/CSS/cssQRAsistencia.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Instructor Jesus Marzal Barboza</h1>
            <h4>Consultar Programas de Formacion</h4>
        </div>

        <div class="form-container">
            <!-- <div class="form-field">
                <label for="qr-code">QR de Asistencia</label>
                <input type="text" id="qr-code" placeholder="Ingrese el código de asistencia">
            </div> -->
            <div class="form-field">
                <label for="nombre">Nombre de Programa</label>
                <input type="text" id="date" placeholder="Ingrese el nombre del Programa">
            </div>
            @*<div class="form-field">
                    <label for="environment">Ambiente de Formación</label>
                    <input type="text" id="environment" placeholder="Ingrese el ambiente de formación">
                </div>*@
            <button class="btn">Mostrar Programas</button>
            @*<button class="button">Generar QR</button>*@
        </div>
    </div>
</body>
</html>

Proyecto de Asistencias (2)/Proyecto de Asistencias/Views/InstructorMenu/InasistenciasAprendiz.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>InasistenciasAprendiz</title>
    <link href="~/CSS/cssQRAsistencia.css" rel="stylesheet" />
</head>
<body>

    <div class="container">
        <div class="header">
            <h1>Instructor Jesus Marzal Barboza</h1>
            <h4>Lista de Inasistencias de Aprendices</h4>
        </div>

        <div class="cuadrado">
            <table>
                <tr>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Fecha</th>
                    <th>Ficha</th>
                    <th>Ambiente</th>
                </tr>
                <tr>
                    <td>Juan</td>
                    <td>Pérez</td>
                    <td>2024-05-03</td>
                    <td>2693606</td>
                    <td>ADSO 1</td>
                </tr>
                <!-- Puedes añadir más filas según sea necesario -->
            </table>
        </div>
    </div>


</body>
</html>

Proyecto de Asistencias (2)/Proyecto de Asistencias/Views/InstructorMenu/ListadoCompetencias.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Listado de Competencias</title>

    <link href="~/CSS/cssQRAsistencia.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Instructor Jesus Marzal Barboza</h1>
            <h4>Listado de Competencias</h4>
        </div>

        <div class="cuadrado">
            <table>
                <tr>
                    <th>Nombre de la Comeptencia</th>
                </tr>
                <tr>
                    <td>Ingles</td>
                </tr>
                <tr>
                    <td>TIC</td>
                </tr>
                <tr>
                    <td>TIC</td>
                </tr>
                <tr>
                    <td>TIC</td>
                </tr>
                <tr>
                    <td>TIC</td>
                </tr>
                <tr>
                    <td>TIC</td>
                </tr>
                <tr>
                    <td>TIC</td>
                </tr>
                <tr>
                    <td>TIC</td>
                </tr>
                <tr>
                    <td>TIC</td>
                </tr>
                <tr>
                    <td>TIC</td>
                </tr>
                <tr>
                    <td>TIC</td>
                </tr>
                <tr>
                    <td>TIC</td>
                </tr>
                <tr>
                    <td>TIC</td>
                </tr>
                <tr>
                    <td>TIC</td>
                </tr>





                <!-- Puedes añadir más filas según sea necesario -->
            </table>
        </div>
    </div>
</body>
</html>

Proyecto de Asistencias (2)/Proyecto de Asistencias/Views/InstructorMenu/ListadoProgramas.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Listado de Programas</title>
    <link href="~/CSS/CSSvistasInstructor.css" rel="stylesheet" />
    <link href="~/CSS/cssQRAsistencia.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Instructor Jesus Marzal Barboza</h1>
            <h4>Listado de Programas</h4>
        </div>

        <div class="cuadrado">
            <table>
                <tr>
                    <th>Nombre de Programas </th>
                </tr>
                <tr>
                    <td>Analisis y Desarrollo de Software</td>
                </tr>
                <tr>
                    <td>Mecanica Industrial</td>
                </tr>
                <!-- Puedes añadir más filas según sea necesario -->
            </table>
        </div>
    </div>


    @*<div class="volver-menu">
            <button class="salir" onclick="location.href = 'MenuprincipalInstructor'">Volver al menu</button>
        </div>*@
</body>
</html>

Proyecto de Asistencias (2)/Proyecto de Asistencias/Views/InstructorMenu/MenuprincipalInstructor.cshtml
@{ Layout = null;
    var nombreUsuario = Session["NombreUsuario"] as string ?? "Nombre";
    var apellidoUsuario = Session["ApellidoUsuario"] as string ?? "Apellido";
}

<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
    <title>Menú principal del Instructor</title>
    <link href="~/CSS/CSSvistasInstructor.css" rel="stylesheet" />
    @*<link href="~/CSS/cssQRAsistencia.css" rel="stylesheet" />*@
</head>
<body>
    <header>
    </header>
    <section>


        <div class="container">
            <div class="header">
                <h1>Instructor @nombreUsuario @apellidoUsuario</h1>
                <h2>Menu de Opciones</h2>
            </div>
            <div class="form-container">

                <div class="form-field opciones">
                    @*<button class="button" onclick="location.href = 'VistaAsistencias'">Asistencias</button>*@
                    <button class="button" onclick="location.href = 'VistaInasistencias'">Inasistencias</button>
                    <button class="button" onclick="location.href = 'VistaAsistencias'">Asistencia</button>
                    <button class="button" onclick="location.href = 'QrAsistencias'">Generar código QR para la Asistencia</button>
                    <button class="button" onclick="location.href = 'ConsultarArchivo'">Consultar Archivo Soporte</button>

                </div>

            </div>

        </div>
        <div>
            <button class="boton_salir" onclick="redirectTo('@Url.Action("Login","Login")')">Salir</button>
        </div>
    </section>
   

    <footer>
        Assist.NET
    </footer>
</body>
</html>

Proyecto de Asistencias (2)/Proyecto de Asistencias/Views/InstructorMenu/VistaconsultarInasistencias.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Consultar Inasistencias</title>
</head>
<body>
    <div class="titulo">
        <h1>Consultar Inasistencias</h1>
    </div>
    <div class="container">
        <label>Número de Ficha</label>
        <input class="numeroficha" />
        <button>Mostrar Fichas</button>
    </div>
</body>
</html>