Proyecto de Asistencias (2)/Proyecto de Asistencias/Controllers/AprendizMenuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Libreria_de_conexion;
using Proyecto_de_Asistencias.Sesion;

namespace Proyecto_de_Asistencias.Controllers
{
    [Validar_sesion]
    public class AprendizMenuController : Controller
    {
        string conexion = "data source = JAMB\\SQLEXPRESS; initial catalog = Asistencia; integrated security = true; multipleactiveresultsets=true;";


        // GET: AprendizMenu
        public ActionResult MenuprincipalAprendiz()
        {
            return View();
        }
        public ActionResult Subirarchivo()
        {
            return View(); 
        }
        public ActionResult Consultarasistencias()
        {
            var idAprend = (int)Session["Aprendiz"];
            using (var db = new AsistenciaEntities())
            {

                var aprendices = db.Registro_Asistencias_QR.Where(a => a.idAprendiz == idAprend).Where(a => a.Tipo_Asistencia == true).
                    ToList();
                ViewBag.Aprendiz = aprendices;

            }

            return View(); 
        }
        public ActionResult Consultarinasistencias()
        {
            var idAprend = (int)Session["Aprendiz"];
            using (var db = new AsistenciaEntities())
            {

                var aprendices = db.Registro_Asistencias_QR.Where(a => a.idAprendiz == idAprend).Where(a => a.Tipo_Asistencia == false).
                    ToList();
                db.Registro_Asistencias_QR.Where(a => a.Tipo_Asistencia == false); ViewBag.Aprendiz = aprendices;

            }

            return View(); 
        }
        public ActionResult Archivosoporte()
        {
            return View(); 
        }
        public ActionResult VistaQR()
        {
            return View(); 
        }
        [HttpPost]
        public ActionResult Cargar(HttpPostedFileBase file, int? idAsistencia)
        {
            try
            {
                // Verificar que se haya seleccionado un archivo
                if (file == null || file.ContentLength == 0)
                {
                    TempData["ErrorMessage"] = "Por favor, seleccione un archivo a subir";
                    return RedirectToAction("SubirArchivo");
                }

                // Verificar que se haya ingresado un ID de inasistencia válido
                if (idAsistencia == null || idAsistencia <= 0)
                {
                    TempData["AlertMessage"] = "Por favor, ingrese un ID de inasistencia válido";
                    return RedirectToAction("SubirArchivo");
                }

                // Obtener la extensión del archivo que se ha cargado
                string Extension = Path.GetExtension(file.FileName);

                // Obtener el id del Aprendiz que inició sesión 
                var idAprendiz = (int)Session["Aprendiz"];

                // Verificar si la inasistencia existe y no ha pasado el tiempo límite
                if (!VerificarInasistenciaValida(idAsistencia.Value))
                {
                    TempData["AlertMessage"] = "La inasistencia no es válida o ha pasado el tiempo límite para subir el archivo.";
                    return RedirectToAction("SubirArchivo");
                }

                // Verificar si el ID de la inasistencia coincide con los registros existentes
                if (!VerificarExistenciaInasistencia(idAsistencia.Value))
                {
                    TempData["AlertMessage"] = "El ID de la inasistencia no coincide con los registros existentes.";
                    return RedirectToAction("SubirArchivo");
                }

                // Verificar si ya existe un archivo de soporte para esta inasistencia
                if (!VerificarArchivoSoporte(idAsistencia.Value))
                {
                    TempData["AlertMessage"] = "Ya se ha subido un archivo de soporte para esta inasistencia.";
                    return RedirectToAction("SubirArchivo");
                }

                // Crear un MemoryStream para copiar el contenido del archivo subido
                using (MemoryStream ms = new MemoryStream())
                {
                    file.InputStream.CopyTo(ms);
                    byte[] data = ms.ToArray();

                    // Insertar el archivo en la base de datos
                    using (SqlConnection connection = new SqlConnection(conexion))
                    {
                        SqlCommand cmd = new SqlCommand(@"INSERT INTO Soporte_asistencia (Archivo_soporte, idAprendiz, Extension, idAsistencia) 
                        VALUES (@Archivo_soporte, @idAprendiz, @Extension, @idAsistencia);", connection);

                        cmd.CommandType = CommandType.Text;
                        cmd.Parameters.AddWithValue("@Archivo_soporte", data);
                        cmd.Parameters.AddWithValue("@idAprendiz", idAprendiz);
                        cmd.Parameters.AddWithValue("@Extension", Extension);
                        cmd.Parameters.AddWithValue("@idAsistencia", idAsistencia.Value);

                        connection.Open();
                        cmd.ExecuteNonQuery();
                        TempData["Mensaje"] = "Archivo Subido Correctamente";
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["AlertMessage"] = "Error al subir el archivo: " + ex.Message;
            }

            return RedirectToAction("SubirArchivo");
        }

        // Método para verificar si la inasistencia es válida y no ha pasado el tiempo límite
        private bool VerificarInasistenciaValida(int idAsistencia)
        {
            try
            {
                using (SqlConnection connection = new SqlConnection(conexion))
                {
                    SqlCommand cmd = new SqlCommand(@"SELECT COUNT(*) 
                                                  FROM Registro_Asistencias_QR
                                                  WHERE idAsistencia = @idAsistencia 
                                                  AND Fecha_Asistencia >= DATEADD(day, -3, GETDATE())", connection);
                    cmd.Parameters.AddWithValue("@idAsistencia", idAsistencia);
                    connection.Open();
                    int count = (int)cmd.ExecuteScalar();
                    return count == 1;
                }
            }
            catch (Exception)
            {
                return false;
            }
        }

        // Método para verificar si ya existe un archivo de soporte para la inasistencia
        private bool VerificarArchivoSoporte(int idAsistencia)
        {
            try
            {
                using (SqlConnection connection = new SqlConnection(conexion))
                {
                    SqlCommand cmd = new SqlCommand(@"SELECT COUNT(*) 
                                                  FROM Soporte_asistencia 
                                                  WHERE idAsistencia = @idAsistencia", connection);
                    cmd.Parameters.AddWithValue("@idAsistencia", idAsistencia);
                    connection.Open();
                    int count = (int)cmd.ExecuteScalar();
                    return count == 0; // Retorna true si no hay archivos de soporte para esta inasistencia
                }
            }
            catch (Exception)
            {
                return false;
            }
        }
        // Método para verificar si el ID de la inasistencia existe en la base de datos
        private bool VerificarExistenciaInasistencia(int idAsistencia)
        {
            try
            {
                using (SqlConnection connection = new SqlConnection(conexion))
                {
                    SqlCommand cmd = new SqlCommand(@"SELECT COUNT(*) 
                                                  FROM Registro_Asistencias_QR
                                                  WHERE idAsistencia = @idAsistencia", connection);
                    cmd.Parameters.AddWithValue("@idAsistencia", idAsistencia);
                    connection.Open();
                    int count = (int)cmd.ExecuteScalar();
                    return count == 1; // Retorna true si el ID de la inasistencia existe en la base de datos
                }
            }
            catch (Exception)
            {
                return false;
            }
        }




    }
}

Proyecto de Asistencias (2)/Proyecto de Asistencias/Views/AprendizMenu/Archivo.cshtml
@model IEnumerable<Libreria_de_conexion.Registro_Asistencias_QR>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Archivo</title>
</head>
<body>
    <table id="asistenciasTable">
        <thead>
            <tr>
                <th>
                    Id de Asistencias
                </th>
                <th>
                    Fecha de Asistencias
                </th>
                <th>
                    Hora de Asistencias
                </th>
                <th>
                    Tipo de Asistencias
                </th>
                <th>
                    Nombre
                </th>
                <th>
                    Apellido
                </th>
                <th>
                    Imagen de QR
                </th>
                <th>
                    Competencias
                </th>
                <th>
                    Ficha
                </th>
                <th>
                    Programa de formacion
                </th>
                <th>
                    Archivo
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var inasistencias in Model)
            {
                <tr data-id="@inasistencias.idAsistencia">
                    <td>
                        @inasistencias.idAsistencia
                    </td>
                    <td>
                        @inasistencias.Fecha_Asistencia
                    </td>
                    <td>
                        @inasistencias.Hora_Asistencia
                    </td>
                    <td>
                        @inasistencias.Tipo_Asistencia
                    </td>
                    <td>
                        @inasistencias.Nombres
                    </td>
                    <td>
                        @inasistencias.Apellidos
                    </td>
                    <td>
                        @inasistencias.ImagenQR
                    </td>
                    <td>
                        @inasistencias.Competencias
                    </td>
                    <td>
                        @inasistencias.Ficha
                    </td>
                    <td>
                        @inasistencias.Programa
                    </td>
                    <td>
                        @inasistencias.ArchivoPDF
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <form id="editForm" method="post" action="/Asistencias/Edit">
        <input type="hidden" id="asistenciaId" name="id" />
        <label for="archivo">Archivo:</label>
        <input type="text" id="archivo" name="archivo" />
        <button type="submit">Guardar</button>
    </form>



</body>
</html>
<script>
    document.querySelectorAll('#asistenciasTable tbody tr').forEach(row => {
        row.addEventListener('click', () => {
            const id = row.getAttribute('data-id');
            document.getElementById('asistenciaId').value = id;
        });
    });
</script>

Proyecto de Asistencias (2)/Proyecto de Asistencias/Views/AprendizMenu/Archivosoporte.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Inasistencias</title>
    <link href="~/CSS/EstiloArchivo.css" rel="stylesheet" />
    <link href="~/CSS/cssQRAsistencia.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Inasistencias de Aprendices</h1>
            <h4>Listado de inasistencias</h4>
        </div>

        <div class="cuadrado">
            <table>
                <tr>
                    <th>Nombre </th>
                    <th>Apellido</th>
                    <th>Fecha</th>
                    <th>Ficha</th>

                </tr>
                <tr>
                </tr>

                <!-- Puedes añadir más filas según sea necesario -->
            </table>
        </div>
        </div>
        <div id="botones" class="boton-opciones">
            <div class="">
                <button class="button" onclick="redirectTo('SubirArchivo')">Seleccionar inasistencias</button>
            </div>
            <div class="">
                <button class="button" onclick="redirectTo('Consultarinasistencias')">Regresar</button>
            </div>
        </div>

        @*<footer id="Bot"> Proyecto asistencia © </footer>*@
</body>
</html>
<script>
    function redirectTo(url) {
        // Agrega una clase de transición al cuerpo del documento
        document.body.classList.add('transicion-salida');

        // Espera un momento antes de redirigir
        setTimeout(function () {
            window.location.href = url;
        }, 500); // Ajusta el tiempo según tu preferencia
    }
</script>

Proyecto de Asistencias (2)/Proyecto de Asistencias/Views/AprendizMenu/Consultarasistencias.cshtml
@{ Layout = null;
    var nombreUsuario = Session["NombreUsuario"] as string ?? "Nombre";
    var apellidoUsuario = Session["ApellidoUsuario"] as string ?? "Apellido";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Consultarasistencias</title>
    @*<link href="~/CSS/EstiloConsultarA.css" rel="stylesheet" />
        <link href="~/CSS/cssIndex.css" rel="stylesheet" />*@
    <link href="~/CSS/VistaAprendiz.css" rel="stylesheet" />

</head>
<body>
    <header>
    </header>
    <section>
        <div class="container">
            <div class="header">
                <h1>Apendiz @nombreUsuario @apellidoUsuario</h1>
                <h4>Consultar Asistencias</h4>
            </div>
            <div class="cuadrado">
                <table>
                    <tr>
                        @**<th>Id de Asistencia</th>*@
                        <th>Fecha de Asistencia</th>
                        <th>Hora de Asistencia</th>
                        <th>Tipo de Asistencia</th>
                        <th>Nombre de Aprendiz</th>
                        <th>Apellidos de Aprendiz</th>
                        <th>Imagen QR</th>
                        <th>Competencias</th>
                        <th>Ficha</th>
                        <th>Programa de Formacion</th>

                    </tr>
                    @foreach (var aprendiz in ViewBag.Aprendiz)
                    {
        <tr>

            @*<td>@aprendiz.idAsistencia</td>*@
            <td>@aprendiz.Fecha_Asistencia</td>
            <td>@aprendiz.Hora_Asistencia</td>
            <td>Asistio</td>
            <td>@aprendiz.Nombres</td>
            <td>@aprendiz.Apellidos</td>
            <td>@aprendiz.ImagenQR</td>
            <td>@aprendiz.Competencias</td>
            <td>@aprendiz.Ficha</td>
            <td>@aprendiz.Programa</td>

        </tr>}
                </table>


            </div>

            <div id="botones">


                <div class="volver">
                    <button class="boton-transicion" onclick="redirectTo('MenuprincipalAprendiz')">Volver</button>
                </div>
            </div>
        </div>

    </section>
    <footer>
        Assist.NET
    </footer>

</body>
</html>
<script>
    function redirectTo(url) {
        // Agrega una clase de transición al cuerpo del documento
        document.body.classList.add('transicion-salida');

        // Espera un momento antes de redirigir
        setTimeout(function () {
            window.location.href = url;
        }, 500); // Ajusta el tiempo según tu preferencia
    }
</script>

Proyecto de Asistencias (2)/Proyecto de Asistencias/Views/AprendizMenu/Consultarinasistencias.cshtml
@{ Layout = null;
    var nombreUsuario = Session["NombreUsuario"] as string ?? "Nombre";
    var apellidoUsuario = Session["ApellidoUsuario"] as string ?? "Apellido";
}

<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Consultarinasistencias</title>
    @*<link href="~/CSS/EstiloConsultarI.css" rel="stylesheet" />
        <link href="~/Content/CSSvistasInstructor.css" rel="stylesheet" />
        <link href="~/CSS/cssQRAsistencia.css" rel="stylesheet" />*@
    <link href="~/CSS/VistaAprendiz.css" rel="stylesheet" />


</head>
<body>
    <header>
    </header>
    <section>


        <div class="container">
            <div class="header">
                <h1>Apendiz @nombreUsuario @apellidoUsuario</h1>
                <h4>Consultar Inasistencias</h4>
            </div>
            <div class="cuadrado">
                <table>
                    <tr>
                        <th>Id de Asistencia</th>
                        <th>Fecha de Asistencia</th>
                        <th>Hora de Asistencia</th>
                        <th>Tipo de Asistencia</th>
                        <th>Nombre de Aprendiz</th>
                        <th>Apellidos de Aprendiz</th>
                        <th>Imagen QR</th>
                        <th>Competencias</th>
                        <th>Ficha</th>
                        <th>Programa de Formacion</th>

                    </tr>
                    @foreach (var aprendiz in ViewBag.Aprendiz)
                    {
                        <tr>

                            <td>@aprendiz.idAsistencia</td>
                            <td>@aprendiz.Fecha_Asistencia</td>
                            <td>@aprendiz.Hora_Asistencia</td>
                            <td>Inasistencia</td>
                            <td>@aprendiz.Nombres</td>
                            <td>@aprendiz.Apellidos</td>
                            <td>@aprendiz.ImagenQR</td>
                            <td>@aprendiz.Competencias</td>
                            <td>@aprendiz.Ficha</td>
                            <td>@aprendiz.Programa</td>

                        </tr>
                    }

                    <!-- Puedes añadir más filas según sea necesario -->
                </table>


            </div>

            <div id="botones">
                <div class="">
                    <button class="button" onclick="redirectTo('SubirArchivo')">Subir archivo de soporte</button>
                </div>

                <div class="volver">
                    <button class="boton-transicion" onclick="redirectTo('MenuprincipalAprendiz')">Volver</button>
                </div>
            </div>
        </div>
    </section>

    <footer> Proyecto asistencia © </footer>
</body>
</html>
<script>
    function redirectTo(url) {
        // Agrega una clase de transición al cuerpo del documento
        document.body.classList.add('transicion-salida');

        // Espera un momento antes de redirigir
        setTimeout(function () {
            window.location.href = url;
        }, 500); // Ajusta el tiempo según tu preferencia
    }
</script>

Proyecto de Asistencias (2)/Proyecto de Asistencias/Views/AprendizMenu/FormularioAsistencias.cshtml
@{
    ViewBag.Title = "Formulario de Asistencias";
    string fecha = Request.QueryString["fecha"];
    string hora = Request.QueryString["hora"];
    int fichaId = int.Parse(Request.QueryString["fichaId"]);
    string programa = Request.QueryString["nameprog"];
    string competencia = Request.QueryString["namecompe"];
    int instructorId = int.Parse(Request.QueryString["instructorId"]);
    string uniqueId = Request.QueryString["id"];
    int aprendizId = (int)Session["Aprendiz"]; // Obtener el ID del aprendiz de la sesión+
    Layout = null;
}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title class="title">@ViewBag.Title</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f9f9f9;
        }

        /* Style the form container */
        .container {
            max-width: 500px;
            margin: 40px auto;
            padding: 20px;
            border: 1px solid #34C759; /* Green border */
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        /* Style the form title */
        h1 {
            text-align: center;
            margin-bottom: 20px;
            font-size: 24px;
            color: #34C759; /* Green color */
        }

        /* Style the form fields */
        label {
            display: block;
            margin-bottom: 10px;
        }

        input, select {
            width: calc(100% - 22px); /* Ajuste para centrar los inputs */
            height: 40px;
            margin: 0 auto 20px; /* Ajuste para centrar los inputs */
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            display: block; /* Asegura que los inputs estén en una línea */
        }

            input:focus, select:focus {
                border-color: #34C759;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            }

            /* Cambiar el borde a verde cuando se hace clic en el input */
            input[type="text"]:focus, input[type="date"]:focus, select:focus {
                border-color: #0de64e;
            }

        /* Style the submit button */
        button[type="submit"] {
            background-color: #34C759;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            display: block; /* Asegura que el botón esté en una línea */
            margin: 0 auto; /* Ajuste para centrar el botón */
        }

            button[type="submit"]:hover {
                background-color: #2E865F;
            }

        /* Style the confirmation and error messages */
        #confirmationMessage, #errorMessage {
            text-align: center;
            margin-top: 20px;
        }

        #confirmationMessage {
            color: green;
        }

        #errorMessage {
            color: red;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Formulario de Asistencias</h1>
        <form id="asistenciaForm">
            <input type="hidden" name="fecha" value="@fecha" />
            <input type="hidden" name="hora" value="@hora" />
            <input type="hidden" name="fichaId" value="@fichaId" />
            <input type="hidden" name="programa" value="@programa" />
            <input type="hidden" name="competencia" value="@competencia" />
            <input type="hidden" name="instructorId" value="@instructorId" />
            <input type="hidden" name="uniqueId" value="@uniqueId" />
            <input type="hidden" name="aprendizId" value="@aprendizId" />

            <div class="form-group">
                <label for="nombres">Nombres:</label>
                <input type="text" id="nombres" name="nombres" required />
            </div>
            <div class="form-group">
                <label for="apellidos">Apellidos:</label>
                <input type="text" id="apellidos" name="apellidos" required />
            </div>
            <button type="submit">Registrar Asistencia</button>
        </form>
        <div id="confirmationMessage" style="display:none;">La asistencia ha sido registrada exitosamente.</div>
        <div id="errorMessage" style="display:none;">Error al registrar la asistencia: Datos de aprendiz incorrectos.</div>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#asistenciaForm').on('submit', function (e) {
                e.preventDefault(); // Prevent the form from submitting via the browser

                $.ajax({
                    url: '@Url.Action("RegistrarAsistencia", "AprendizMenu")',
                    type: 'POST',
                    data: $(this).serialize(),
                    success: function (response) {
                        if (response.success) {
                            $('#confirmationMessage').text(response.message).show(); // Show confirmation message
                            $('#errorMessage').hide(); // Hide error message
                        } else {
                            $('#errorMessage').text(response.message).show(); // Show error message
                            $('#confirmationMessage').hide(); // Hide confirmation message
                        }
                    },
                    error: function () {
                        $('#errorMessage').text('Error al registrar la asistencia.').show(); // Show generic error message
                        $('#confirmationMessage').hide(); // Hide confirmation message
                    }
                });
            });
        });
    </script>
</body>
</html>

Proyecto de Asistencias (2)/Proyecto de Asistencias/Views/AprendizMenu/MostrarQR.cshtml
@{
    Layout = null;
    ViewBag.Title = "Ver QR de Asistencias";
    int idUsuario = ViewBag.IdUsuario; // Obtén el ID del usuario desde el ViewBag
}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Aprendiz - Código QR de Asistencias</h1>
        </div>
        <div class="qr-container" id="qr-container">
            <h4>Código QR:</h4>
            <img id="qr-image" src="@Url.Action("ObtenerImagenQR", "AprendizMenu" , new { idUser = idUsuario })" alt="Código QR">
        </div>
        <div id="mensaje-container" class="mensaje-container" style="display:none;">
            <h4>El código QR ya no está disponible.</h4>
        </div>
    </div>

    <script type="text/javascript">
        function verificarDisponibilidadQR() {
            $.ajax({
                url: '@Url.Action("VerificarDisponibilidadQR", "AprendizMenu", new { idUser = idUsuario })',
                type: 'GET',
                success: function (data) {
                    if (!data.disponible) {
                        $('#qr-container').hide();
                        $('#mensaje-container').show();
                    }
                },
                error: function () {
                    console.error('Error al verificar la disponibilidad del QR.');
                }
            });
        }

        // Verificar la disponibilidad del QR cada 5 segundos
        setInterval(verificarDisponibilidadQR, 1000);
    </script>
</body>
</html>

Proyecto de Asistencias (2)/Proyecto de Asistencias/Views/AprendizMenu/Subirarchivo.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="en">
<head>
    @*<link href="~/Content/Estilos de las vistas de Aprendiz/EstiloSubir.css" rel="stylesheet" />*@
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SubirArchivo</title>
    @*<link href="~/CSS/cssIndex.css" rel="stylesheet" />*@
    <link href="~/CSS/VistaAprendiz.css" rel="stylesheet" />
</head>
<body>
    <header>
    </header>
    <section>

        <div class="container modal" id="mymodal">
            <div class="header">
                <h1>Archivo de soporte de inasistencia</h1>
                <h2>Subir Archivo</h2>
            </div>
            <div class="form-container">
                <form action="@Url.Action("Cargar", "AprendizMenu")" method="post" enctype="multipart/form-data" id="uploadForm">
                    <div class="form-field">
                        <input type="text" name="idAsistencia" id="idAsistencia" placeholder="Ingrese el id de Asistencia" value="" onblur="verificarFecha()" />
                        <div class="boton-files">
                            <input type="file" name="file" id="file" accept=".pdf" onchange="AbrirExpliorer(this)" />
                        </div>
                    </div>
                    <div class="form-field modal-buttons">
                        <button type="submit" value="Subir Archivo" class="button" id="uploadButton">Subir Archivo</button>
                    </div>
                    <div class="mensaje-archivo">
                        <h5>Informacion de la Asistencia</h5>
                        @if (TempData["AlertMessage"] != null)
                        {
                            <div class="alert alert-danger">
                                @TempData["AlertMessage"]
                            </div> }
                        else
                        {
                            <div class="correcto">
                                @TempData["Mensaje"]
                            </div>}
                    </div>
                </form>
            </div>
            <div class="volver">
                <button class="button boton-transicion" onclick="redirectTo('Consultarinasistencias')">Volver</button>
            </div>
        </div>
    </section>
    <footer> Proyecto asistencia © </footer>

    <script>
        function AbrirExpliorer(a) {
            if (a.files && a.files[0]) {
                var file = a.files[0];
                if (file.type !== "application/pdf") {
                    alert("Solo se permiten archivos PDF");
                    a.value = "";
                    return;
                }
                var reader = new FileReader();
                reader.onload = function (e) {
                    document.getElementById('Archivo').innerHTML = '<p>' + file.name + '<p>';
                }
                reader.readAsDataURL(file);
            }
        }

        function redirectTo(url) {
            document.body.classList.add('transicion-salida');
            setTimeout(function () {
                window.location.href = url;
            }, 500);
        }
    </script>
</body>
</html>

Proyecto de Asistencias (2)/Proyecto de Asistencias/Views/AprendizMenu/VistaQR.cshtml
@{ Layout = null;
    var nombreUsuario = Session["NombreUsuario"] as string ?? "Nombre";
    var apellidoUsuario = Session["ApellidoUsuario"] as string ?? "Apellido";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>VistaQR</title>
    <link href="~/CSS/VistaAprendiz.css" rel="stylesheet" />
</head>
<body>
    <header>
    </header>
    <section>


        <div class="container">
            <div class="header">
                <h1>Aprendiz @nombreUsuario @apellidoUsuario</h1>
                <h4>QR Generado</h4>
            </div>
            <div class="form-container">

                <div class="cuadrado">

                </div>
            </div>
            <div class="">
                <button class="button-salir" onclick="location.href = 'MenuprincipalAprendiz'">Volver</button>
            </div>
        </div>
    </section>
    <footer>
        Assist.NET
    </footer>
</body>
</html>