Proyecto de Asistencias (2)/Proyecto de Asistencias/Controllers/Programa_FormacionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Libreria_de_conexion;
using Proyecto_de_Asistencias.Sesion;

namespace Proyecto_de_Asistencias.Controllers
{
    [Validar_sesion]
    public class Programa_FormacionController : Controller
    {
        private AsistenciaEntities db = new AsistenciaEntities();

        // GET: Programa_Formacion
        public ActionResult Index(string buscar)
        {
            var programa_Formacion = db.Programa_Formacion.Include(p => p.Administrador);

            if (!String.IsNullOrEmpty(buscar))
            {
                // Asumiendo que quieres buscar por un campo 'Nombre' en la entidad 'Programa_Formacion'
                programa_Formacion = programa_Formacion.Where(p => p.Nombre_Programa.Contains(buscar));
            }

            return View(programa_Formacion.ToList());
        }


        // GET: Programa_Formacion/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Programa_Formacion programa_Formacion = db.Programa_Formacion.Find(id);
            if (programa_Formacion == null)
            {
                return HttpNotFound();
            }
            return View(programa_Formacion);
        }

        // GET: Programa_Formacion/Create
        public ActionResult Create()
        {
            ViewBag.idAdministrador = new SelectList(db.Administrador, "idAdministrador", "idAdministrador");
            return View();
        }

        // POST: Programa_Formacion/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idPrograma,Nombre_Programa,Duracion_Programa,idAdministrador")] Programa_Formacion programa_Formacion)
        {
            if (ModelState.IsValid)
            {
                db.Programa_Formacion.Add(programa_Formacion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idAdministrador = new SelectList(db.Administrador, "idAdministrador", "idAdministrador", programa_Formacion.idAdministrador);
            return View(programa_Formacion);
        }

        // GET: Programa_Formacion/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Programa_Formacion programa_Formacion = db.Programa_Formacion.Find(id);
            if (programa_Formacion == null)
            {
                return HttpNotFound();
            }
            ViewBag.idAdministrador = new SelectList(db.Administrador, "idAdministrador", "idAdministrador", programa_Formacion.idAdministrador);
            return View(programa_Formacion);
        }

        // POST: Programa_Formacion/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idPrograma,Nombre_Programa,Duracion_Programa,idAdministrador")] Programa_Formacion programa_Formacion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(programa_Formacion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idAdministrador = new SelectList(db.Administrador, "idAdministrador", "idAdministrador", programa_Formacion.idAdministrador);
            return View(programa_Formacion);
        }

        // GET: Programa_Formacion/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Programa_Formacion programa_Formacion = db.Programa_Formacion.Find(id);
            if (programa_Formacion == null)
            {
                return HttpNotFound();
            }
            return View(programa_Formacion);
        }

        // POST: Programa_Formacion/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Programa_Formacion programa_Formacion = db.Programa_Formacion.Find(id);
            db.Programa_Formacion.Remove(programa_Formacion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Proyecto de Asistencias (2)/Proyecto de Asistencias/Views/Programa_Formacion/Create.cshtml
@model Libreria_de_conexion.Programa_Formacion

@{
    ViewBag.Title = "Create";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/Botones_y_textos.css" rel="stylesheet" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Programa_Formacion</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                   <a class="nombre">Id programa</a>
            <div class="col-md-10">
                @Html.EditorFor(model => model.idPrograma, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.idPrograma, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <a class="nombre">Nombre</a>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre_Programa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre_Programa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <a class="nombre">Duracion</a>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duracion_Programa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duracion_Programa, "", new { @class = "text-danger" })
            </div>
        </div>
    
            <div class="form-group">
                    <a class="nombre">Identificacion admin</a>
                <div class="col-md-10">
                    @Html.DropDownList("idAdministrador", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.idAdministrador, "", new { @class = "text-danger" })
                </div>
            </div>
    
             <br />
            <div class="form-group button-container">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Guardar" class="btn-guardar" />
                    <input type="button" class="input-volver" value="Volver" onclick="location.href='@Url.Action("Index")'" />
            </div>
        </div>
        </div>
    }
    
  
</body>
</html>

Proyecto de Asistencias (2)/Proyecto de Asistencias/Views/Programa_Formacion/Delete.cshtml
@model Libreria_de_conexion.Programa_Formacion

@{
    ViewBag.Title = "Delete";
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/Botones_y_textos.css" rel="stylesheet" />

    <title>Delete</title>
</head>
<body>
   
    <div>
        <h4>Programa_Formacion</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                <a class="nombre">Nombre</a>
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nombre_Programa)
            </dd>

            <dt>
                <a class="nombre">Duracion</a>
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Duracion_Programa)
            </dd>

            <dt>
                <a class="nombre">Identificacion admin</a>
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Administrador.idAdministrador)
            </dd>

           

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

           <div class="form-actions no-color">
                <input type="submit" value="Eliminar" class="btn-Eliminar" />
                <input type="button" class="input-volver" value="Volver" onclick="location.href='@Url.Action("Index")'" />
            </div>
        }
    </div>
</body>
</html>

Proyecto de Asistencias (2)/Proyecto de Asistencias/Views/Programa_Formacion/Details.cshtml
@model Libreria_de_conexion.Programa_Formacion

@{
    ViewBag.Title = "Detalles";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/Botones_y_textos.css" rel="stylesheet" />

    <title>Details</title>
</head>
<body>
    <div>
        <h4>Programa_Formacion</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                <a class="nombre">Nombre</a>
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Nombre_Programa)
            </dd>
    
            <dt>
                <a class="nombre">Duracion</a>
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Duracion_Programa)
            </dd>
    
            <dt>
                <a class="nombre">Identificacion admin</a>
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Administrador.idAdministrador)
            </dd>
    
        </dl>
    </div>
    <div class="col-md-offset-2 col-md-10">
        <input type="button" class="btn-Editar" value="Editar" onclick="location.href='@Url.Action("Edit", new { id = Model.idPrograma })'" />
        <input type="button" class="input-volver" value="Volver" onclick="location.href='@Url.Action("Index")'" />

    </div>
</body>
</html>

Proyecto de Asistencias (2)/Proyecto de Asistencias/Views/Programa_Formacion/Edit.cshtml
@model Libreria_de_conexion.Programa_Formacion

@{
    ViewBag.Title = "Edit";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/Botones_y_textos.css" rel="stylesheet" />
    <title>Editar</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Programa_Formacion</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.idPrograma)
    
            <div class="form-group">
                <a class="nombre">Nombre</a>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nombre_Programa, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nombre_Programa, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <a class="nombre">Duracion</a>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Duracion_Programa, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Duracion_Programa, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <a class="nombre">Identificacion admin</a>               
                <div class="col-md-10">
                    @Html.DropDownList("idAdministrador", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.idAdministrador, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <br />
            <div class="form-group button-container">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Guardar" class="btn-guardar" />
                    <input type="button" class="input-volver" value="Volver" onclick="location.href='@Url.Action("Index")'" />
                </div>
            </div>
        </div>
    }
    
  
</body>
</html>

Proyecto de Asistencias (2)/Proyecto de Asistencias/Views/Programa_Formacion/Index.cshtml
@model IEnumerable<Libreria_de_conexion.Programa_Formacion>

@{
    ViewBag.title = "Programa"; 
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/CSS/Botonesprincipales_tablas.css" rel="stylesheet" />
    <link href="~/Content/Estilo_tablas.css" rel="stylesheet" />
</head>

<style>
    .welcome {
        text-align: center;
        padding: 10px;
        padding-top: 10px;
        background-color: #3DAF04;
        border-radius: 15px;
        color: white;
        font-family: 'Poppins', sans-serif;
    }
</style>
<body>
    <br />
    <h2 class="welcome">Programas de Formacion</h2>
    <div class="action-bar">
        <p>
            @Html.ActionLink("Nuevo Programa", "Create", "", new { @class = "btn-nuevo" })
        </p>
        <form asp-controller="Programa_Formacion" asp-action="Index" method="get">
            <p>
                <input type="text" name="buscar" class="caja-texto" />
                <input type="submit" value="Buscar" class="btn-buscar" />

            </p>

        </form>
    </div>
        <div class="table-responsive">


            <table class="table">
                <tr>
                    <th>
                        ID
                    </th>
                    <th>
                        Nombre
                    </th>
                    <th>
                        Duracion
                    </th>
                    <th>
                        Identificacion admin
                    </th>
                    <th>Operaciones</th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.idPrograma)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nombre_Programa)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Duracion_Programa)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Administrador.idAdministrador)
                        </td>
                        <td>
                            @Html.ActionLink("Editar", "Edit", new { id = item.idPrograma }, new { @class = "btn-editar" })
                            @Html.ActionLink("Detalles", "Details", new { id = item.idPrograma }, new { @class = "btn-detalles" })
                            @Html.ActionLink("Eliminar", "Delete", new { id = item.idPrograma }, new { @class = "btn-eliminar" })
                        </td>
                    </tr>
                }

            </table>
        </div>
</body>
</html>